repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
  - repo: local
    hooks:
      - id: test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
